In [ ]:
'''Goal
Demonstrate data analysis skills using Pandas.

Requirements
Load and inspect a CSV dataset
Clean missing or incorrect data
Apply filtering, grouping, and aggregation
Explain insights in simple words

In [10]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

print(pd.__version__)

3.0.3

In [2]:
import pandas as pd

data = pd.read_csv(r"D:\Hr dataset\HR_Dataset.csv")

In [3]:
data.head()

,Employee_ID,Department,Gender,Age,Education_Level,Job_Role,Monthly_Income,Years_At_Company,Years_In_Current_Role,Job_Satisfaction,Performance_Rating,Work_Life_Balance,Training_Hours_Last_Year,Last_Promotion_Years_Ago,Distance_From_Home,Overtime,Attrition,Marital_Status,Number_Of_Companies_Worked,Stock_Option_Level
0,1001,Sales,Female,28,Bachelor's Degree,Analyst,3822.0,23,0,3,2,1,24,3,29,Yes,No,Married,7,2
1,1002,Marketing,Female,36,Master's Degree,Manager,10125.0,31,11,1,1,5,61,1,14,No,Yes,Divorced,8,0
2,1003,Finance,Non-binary,28,PhD,Analyst,3256.0,33,12,3,5,1,83,11,2,Yes,Yes,Divorced,7,3
3,1004,Marketing,Male,18,High School,Intern,1279.0,0,0,3,3,4,0,0,48,Yes,No,Single,1,0
4,1005,Marketing,Non-binary,55,Bachelor's Degree,Team Lead,8221.0,1,4,1,3,3,1,7,22,Yes,No,Divorced,9,3

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_ID                 3400 non-null   int64
 1   Department                  3400 non-null   str
 2   Gender                      3400 non-null   str
 3   Age                         3400 non-null   int64
 4   Education_Level             3400 non-null   str
 5   Job_Role                    3400 non-null   str
 6   Monthly_Income              3400 non-null   float64
 7   Years_At_Company            3400 non-null   int64
 8   Years_In_Current_Role       3400 non-null   int64
 9   Job_Satisfaction            3400 non-null   int64
 10  Performance_Rating          3400 non-null   int64
 11  Work_Life_Balance           3400 non-null   int64
 12  Training_Hours_Last_Year    3400 non-null   int64
 13  Last_Promotion_Years_Ago    3400 non-null   int64
 14  Distance_From_Home          3400 non-null   int64
 15  Overtime                    3400 non-null   str
 16  Attrition                   3400 non-null   str
 17  Marital_Status              3400 non-null   str
 18  Number_Of_Companies_Worked  3400 non-null   int64
 19  Stock_Option_Level          3400 non-null   int64
dtypes: float64(1), int64(12), str(7)
memory usage: 531.4 KB

In [5]:
data.describe()

,Employee_ID,Age,Monthly_Income,Years_At_Company,Years_In_Current_Role,Job_Satisfaction,Performance_Rating,Work_Life_Balance,Training_Hours_Last_Year,Last_Promotion_Years_Ago,Distance_From_Home,Number_Of_Companies_Worked,Stock_Option_Level
count,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.000000,3400.00000,3400.000000
mean,2700.500000,38.370882,5125.363235,15.784706,7.514706,3.042059,3.040588,3.002059,39.720294,5.675000,25.100882,4.18500,1.192647
std,981.639785,13.721319,3224.822138,12.954993,6.373933,1.422406,1.415295,1.414732,32.544983,4.752908,14.019051,2.77946,1.173255
min,1001.000000,18.000000,1000.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.00000,0.000000
25%,1850.750000,24.000000,2391.750000,2.000000,1.000000,2.000000,2.000000,2.000000,6.000000,1.000000,13.000000,1.00000,0.000000
50%,2700.500000,38.000000,4326.000000,15.000000,7.000000,3.000000,3.000000,3.000000,38.000000,5.000000,25.000000,4.00000,1.000000
75%,3550.250000,51.000000,7961.250000,27.000000,13.000000,4.000000,4.000000,4.000000,68.000000,10.000000,37.000000,7.00000,2.000000
max,4400.000000,59.000000,12000.000000,39.000000,19.000000,5.000000,5.000000,5.000000,99.000000,14.000000,49.000000,9.00000,3.000000

In [6]:
# check anu null value is in HR dataset
data.isnull().sum()  #No missing value found in dataset

Employee_ID                   0
Department                    0
Gender                        0
Age                           0
Education_Level               0
Job_Role                      0
Monthly_Income                0
Years_At_Company              0
Years_In_Current_Role         0
Job_Satisfaction              0
Performance_Rating            0
Work_Life_Balance             0
Training_Hours_Last_Year      0
Last_Promotion_Years_Ago      0
Distance_From_Home            0
Overtime                      0
Attrition                     0
Marital_Status                0
Number_Of_Companies_Worked    0
Stock_Option_Level            0
dtype: int64

In [11]:
#Avg salary per department
avg_sal= data.groupby('Department')['Monthly_Income'].mean()
print(avg_sal)

Department
Finance      5186.178737
HR           5203.394245
IT           5152.896024
Marketing    5021.205421
Sales        5070.166904
Name: Monthly_Income, dtype: float64

In [13]:
#Avg salary per department in asc
avg_salary=data.groupby('Department')['Monthly_Income'].mean().round(2).sort_values(ascending = False) #HR department is the highest avg paid salary
print(avg_salary)

Department
HR           5203.39
Finance      5186.18
IT           5152.90
Sales        5070.17
Marketing    5021.21
Name: Monthly_Income, dtype: float64

In [24]:
Highest_salary = data.loc[data['Monthly_Income'].idxmax(),['Employee_ID','Monthly_Income']] #IT GIVES HIGHEST SALARY BY EMPLOYEEE_ID
print(Highest_salary)

Employee_ID        1204.0
Monthly_Income    12000.0
Name: 203, dtype: float64

In [31]:
#top 10 highest paid salary  
top_10 = data[['Employee_ID','Monthly_Income']].sort_values(by='Monthly_Income',ascending = False).head(10)
print(top_10.to_string(index=False))

 Employee_ID  Monthly_Income
        2514         12000.0
        1204         12000.0
        1237         11998.0
        1313         11992.0
        1947         11974.0
        3813         11966.0
        1717         11959.0
        2118         11952.0
        2457         11946.0
        3776         11921.0

In [38]:
#salary greater than 10000
emp = data.loc[data['Monthly_Income'] >10000,['Employee_ID','Monthly_Income']]
print(emp.to_string(index=False))
print('Number of employee earning more than 10000 :' ,len(emp))

#output
# There are 272 employee who earning morethan 10000

 Employee_ID  Monthly_Income
        1002         10125.0
        1007         10853.0
        1015         10376.0
        1023         11816.0
        1036         11102.0
        1055         11055.0
        1062         10260.0
        1079         11637.0
        1085         11774.0
        1108         11778.0
        1143         10675.0
        1157         10813.0
        1181         11671.0
        1204         12000.0
        1207         11145.0
        1209         10593.0
        1237         11998.0
        1241         10431.0
        1249         11330.0
        1251         11842.0
        1257         11138.0
        1260         11477.0
        1266         11498.0
        1267         10441.0
        1270         11149.0
        1287         11874.0
        1313         11992.0
        1314         10373.0
        1324         10690.0
        1325         10145.0
        1339         10044.0
        1341         11664.0
        1344         11164.0
        1353         10269.0
        1364         11283.0
        1384         10118.0
        1388         10571.0
        1401         11255.0
        1411         11100.0
        1414         11476.0
        1421         10755.0
        1425         11399.0
        1432         10035.0
        1444         10742.0
        1457         11367.0
        1462         11218.0
        1480         11606.0
        1494         10438.0
        1500         11815.0
        1513         10465.0
        1514         11698.0
        1518         11311.0
        1538         10040.0
        1544         10551.0
        1556         11362.0
        1579         11016.0
        1607         11407.0
        1613         10664.0
        1622         10205.0
        1623         11650.0
        1626         10251.0
        1638         10005.0
        1643         10916.0
        1652         11653.0
        1656         11776.0
        1665         11832.0
        1677         11045.0
        1698         10333.0
        1717         11959.0
        1722         11251.0
        1727         10281.0
        1749         11419.0
        1792         10733.0
        1809         11417.0
        1819         11650.0
        1823         10105.0
        1826         11209.0
        1845         10079.0
        1854         10601.0
        1858         11668.0
        1861         11178.0
        1892         10622.0
        1895         11416.0
        1910         10757.0
        1911         10240.0
        1930         11464.0
        1938         11851.0
        1947         11974.0
        1950         11743.0
        1957         10609.0
        1991         11884.0
        1992         10236.0
        1995         11368.0
        2052         10027.0
        2081         10909.0
        2088         11265.0
        2117         10967.0
        2118         11952.0
        2130         10732.0
        2166         11619.0
        2168         10426.0
        2191         10850.0
        2192         10937.0
        2194         11628.0
        2206         10758.0
        2208         10148.0
        2216         10426.0
        2239         11179.0
        2254         11752.0
        2265         11152.0
        2274         10783.0
        2279         11496.0
        2298         11612.0
        2311         11544.0
        2316         10131.0
        2318         10151.0
        2319         11095.0
        2330         10624.0
        2334         11321.0
        2336         11196.0
        2350         11651.0
        2368         10136.0
        2370         10325.0
        2395         11677.0
        2396         10648.0
        2415         11389.0
        2421         11274.0
        2432         10649.0
        2440         10331.0
        2457         11946.0
        2469         10942.0
        2473         10567.0
        2514         12000.0
        2519         10985.0
        2553         11238.0
        2559         10992.0
        2567         11528.0
        2591         10650.0
        2600         11217.0
        2601         11889.0
        2606         11845.0
        2608         10615.0
        2639         10245.0
        2679         10727.0
        2715         10674.0
        2755         10533.0
        2777         10490.0
        2793         10870.0
        2796         10147.0
        2814         10516.0
        2820         10730.0
        2825         11432.0
        2880         11852.0
        2884         10336.0
        2898         11133.0
        2901         10676.0
        2914         10224.0
        2921         10713.0
        2952         10340.0
        2960         10828.0
        2978         11872.0
        2982         11758.0
        3010         11495.0
        3011         11875.0
        3036         10980.0
        3040         10037.0
        3084         11124.0
        3085         10649.0
        3086         11846.0
        3087         10076.0
        3106         11335.0
        3116         10965.0
        3117         10341.0
        3129         10280.0
        3170         11536.0
        3232         10311.0
        3236         10258.0
        3263         11802.0
        3296         10190.0
        3341         11823.0
        3345         11033.0
        3355         11462.0
        3357         11719.0
        3376         10686.0
        3381         11396.0
        3395         10071.0
        3400         10499.0
        3408         11253.0
        3412         10328.0
        3419         11109.0
        3428         10267.0
        3438         11203.0
        3456         11726.0
        3465         11260.0
        3482         11442.0
        3498         10698.0
        3516         10930.0
        3530         10720.0
        3544         10705.0
        3548         10701.0
        3550         10538.0
        3553         10909.0
        3554         11016.0
        3566         11502.0
        3574         10988.0
        3593         10085.0
        3600         11786.0
        3605         11029.0
        3611         11605.0
        3650         11056.0
        3660         10101.0
        3670         11774.0
        3671         11890.0
        3682         11019.0
        3710         11209.0
        3714         11621.0
        3716         11917.0
        3717         11443.0
        3766         10669.0
        3776         11921.0
        3784         10713.0
        3787         10116.0
        3790         10617.0
        3808         11619.0
        3813         11966.0
        3820         11193.0
        3831         11604.0
        3876         11471.0
        3879         10743.0
        3892         10836.0
        3920         10374.0
        3929         11856.0
        3937         10624.0
        3969         10324.0
        3985         10865.0
        3987         11053.0
        4003         10641.0
        4020         11503.0
        4050         10471.0
        4055         11236.0
        4063         10077.0
        4064         10813.0
        4130         11158.0
        4158         10522.0
        4159         11715.0
        4160         11183.0
        4170         11784.0
        4178         11736.0
        4180         11368.0
        4187         11732.0
        4199         11111.0
        4203         11889.0
        4205         11455.0
        4215         11707.0
        4221         10464.0
        4240         10851.0
        4242         11271.0
        4244         10864.0
        4248         10360.0
        4262         11427.0
        4268         10088.0
        4285         11350.0
        4294         10707.0
        4298         11657.0
        4301         11431.0
        4306         11303.0
        4317         11130.0
        4342         10065.0
        4355         10948.0
        4378         11313.0
        4387         10850.0
        4399         11397.0
Number of employee earning more than 10000 : 272

In [39]:
print(data.columns)

Index(['Employee_ID', 'Department', 'Gender', 'Age', 'Education_Level',
       'Job_Role', 'Monthly_Income', 'Years_At_Company',
       'Years_In_Current_Role', 'Job_Satisfaction', 'Performance_Rating',
       'Work_Life_Balance', 'Training_Hours_Last_Year',
       'Last_Promotion_Years_Ago', 'Distance_From_Home', 'Overtime',
       'Attrition', 'Marital_Status', 'Number_Of_Companies_Worked',
       'Stock_Option_Level'],
      dtype='str')

In [40]:
data['Attrition'].value_counts()
#output
#There are 3400 employee in the company but 1724 employee left the company and 1676 employee still in the company

Attrition
Yes    1724
No     1676
Name: count, dtype: int64

In [41]:
attrition_rate = (data['Attrition'].value_counts(normalize=True)*100).round(2)
print(attrition_rate)
#output
#it gives attrition rate that 50.71% employee left the company and 49.29% employee still work in company 
#It can affect company growth future

Attrition
Yes    50.71
No     49.29
Name: proportion, dtype: float64

In [42]:
data['Department'].value_counts()

Department
Sales        701
Marketing    701
HR           695
IT           654
Finance      649
Name: count, dtype: int64

In [46]:
pd.crosstab(data['Department'],data['Attrition'])

#"A cross-tabulation analysis was performed between Department and Attrition. The Sales department recorded the highest employee attrition (359 employees), while the IT department recorded the lowest attrition (329 employees). Attrition levels were relatively similar across all departments, indicating that employee turnover is distributed fairly evenly throughout the organization."

Attrition    No  Yes
Department
Finance     317  332
HR          342  353
IT          325  329
Marketing   350  351
Sales       342  359